#!/usr/bin/env python3
"""
Check if all backend controller actions (from route files) are registered
in the API permissions seed file (api-permissions.ts).

Strapi has two levels of access control:
  1. Strapi level (users-permissions plugin) - checks if the Authenticated role
     has permission for the controller action. WITHOUT this, the route returns 403.
  2. App policy level (is-super-admin, is-tenant-owner, check-permission) - runs
     AFTER the Strapi-level check passes.

Therefore ALL routes (including super-admin ones) must be registered in
api-permissions.ts. Only auth:false routes bypass the Strapi-level check.

Usage:
    python3 .claude/skills/strapi/scripts/check_permissions.py
"""

import glob
import os
import re
import sys

# Skill lives at .claude/skills/strapi/scripts/ -> project root is 4 levels up
PROJECT_ROOT = os.path.dirname(
    os.path.dirname(
        os.path.dirname(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        )
    )
)
ROUTES_GLOB = os.path.join(PROJECT_ROOT, "backend/src/api/*/routes/*.ts")
PERMISSIONS_FILE = os.path.join(
    PROJECT_ROOT, "backend/src/bootstrap/seeds/api-permissions.ts"
)

# Standard CRUD actions generated by Strapi's createCoreRouter
CORE_ROUTER_ACTIONS = ["find", "findOne", "create", "update", "delete"]


def parse_permissions_seed(filepath):
    """Parse api-permissions.ts to extract controller -> set of actions."""
    with open(filepath, "r") as f:
        content = f.read()

    pattern = re.compile(
        r"\{\s*controller:\s*'([^']+)'\s*,\s*actions:\s*\[([^\]]+)\]",
        re.MULTILINE,
    )

    permissions = {}
    for match in pattern.finditer(content):
        controller = match.group(1)
        actions_str = match.group(2)
        actions = set(re.findall(r"'([^']+)'", actions_str))
        if controller in permissions:
            permissions[controller] |= actions
        else:
            permissions[controller] = actions

    return permissions


def parse_route_file(filepath):
    """Parse a route file to extract handler actions."""
    with open(filepath, "r") as f:
        content = f.read()

    results = []
    rel_path = os.path.relpath(filepath, PROJECT_ROOT)

    # Check if this is a createCoreRouter file
    core_router_match = re.search(
        r"createCoreRouter\(\s*'api::([^.]+)\.", content
    )
    if core_router_match:
        controller = core_router_match.group(1)

        auth_false_actions = set()
        config_block = re.search(
            r"config:\s*\{(.*?)\}\s*\)", content, re.DOTALL
        )
        if config_block:
            config_text = config_block.group(1)
            action_configs = re.finditer(
                r"(\w+)\s*:\s*\{([^}]*)\}", config_text
            )
            for ac_match in action_configs:
                action_name = ac_match.group(1)
                action_config = ac_match.group(2)
                if re.search(r"auth\s*:\s*false", action_config):
                    auth_false_actions.add(action_name)

        for action in CORE_ROUTER_ACTIONS:
            results.append(
                {
                    "controller": controller,
                    "action": action,
                    "auth_false": action in auth_false_actions,
                    "source_file": rel_path,
                }
            )

    # Parse explicit route definitions
    route_blocks = re.split(r"(?=\{\s*\n?\s*method\s*:)", content)

    for block in route_blocks:
        handler_match = re.search(
            r"handler\s*:\s*'([^']+)\.([^']+)'", block
        )
        if not handler_match:
            continue

        controller = handler_match.group(1)
        action = handler_match.group(2)
        auth_false = bool(re.search(r"auth\s*:\s*false", block))

        results.append(
            {
                "controller": controller,
                "action": action,
                "auth_false": auth_false,
                "source_file": rel_path,
            }
        )

    return results


def main():
    print("Checking API permission coverage...\n")

    if not os.path.exists(PERMISSIONS_FILE):
        print("ERROR: Permissions file not found: {}".format(PERMISSIONS_FILE))
        sys.exit(1)

    permissions = parse_permissions_seed(PERMISSIONS_FILE)

    route_files = sorted(glob.glob(ROUTES_GLOB))
    if not route_files:
        print("ERROR: No route files found matching: {}".format(ROUTES_GLOB))
        sys.exit(1)

    all_routes = []
    for rf in route_files:
        all_routes.extend(parse_route_file(rf))

    # De-duplicate
    seen = {}
    for route in all_routes:
        key = (route["controller"], route["action"])
        if key not in seen:
            seen[key] = dict(route)
        else:
            if route["auth_false"]:
                seen[key]["auth_false"] = True

    unique_routes = list(seen.values())

    # Compare
    missing = []
    covered = []
    skipped_public = []

    for route in unique_routes:
        ctrl = route["controller"]
        action = route["action"]

        # Only auth:false routes skip Strapi-level permission check
        if route["auth_false"]:
            skipped_public.append(route)
            continue

        if ctrl in permissions and action in permissions[ctrl]:
            covered.append(route)
        else:
            missing.append(route)

    # Output
    if missing:
        missing.sort(key=lambda r: (r["controller"], r["action"]))
        print("MISSING from api-permissions.ts:")
        for route in missing:
            print(
                "  {}.{} (from {})".format(
                    route["controller"], route["action"], route["source_file"]
                )
            )
        print()

    if skipped_public:
        skipped_public.sort(key=lambda r: (r["controller"], r["action"]))
        print("Skipped (auth: false): {}".format(len(skipped_public)))
        for route in skipped_public:
            print("  {}.{}".format(route["controller"], route["action"]))
        print()

    if not missing:
        print("All controller actions are registered in api-permissions.ts")

    print(
        "Summary: {} missing, {} covered, {} public (auth: false)".format(
            len(missing), len(covered), len(skipped_public)
        )
    )

    sys.exit(1 if missing else 0)


if __name__ == '__main__':
    main()
